export const API_ROUTES = {
  AUTH: {
    LOGIN: "auth/login/admin",
    LOGIN_SUPER_ADMIN: "auth/login/super-admin",
    REGISTER: "auth/register",
    PROFILE: "auth/me",
    CHANGE_PASSWORD: "auth/me/change-password",
    DELETE_PROFILE_PIC: "auth/me/profile-pic",
  },
  ANALYTICS: {
    GET_REPORTS: "admin/analytics/reports",
  },
  SETTINGS: {
    GET: "admin/settings",
    UPDATE: "admin/settings",
  },
  NOTIFICATIONS: {
    GET_ALL: "admin/notifications",
    GET_UNREAD_COUNT: "admin/notifications/unread-count",
    MARK_READ: "admin/notifications/read",
    DELETE: "admin/notifications",
  },
  CATEGORIES: {
    GET_PUBLIC: "public/categories",
    GET_ALL: "admin/categories",
    CREATE: "admin/categories",
    UPDATE: (id) => `admin/categories/${id}`,
    DELETE: (id) => `admin/categories/${id}`,
  },
  SUBJECTS: {
    GET_ALL: "admin/subjects",
    CREATE: "admin/subjects",
    UPDATE: (id) => `admin/subjects/${id}`,
    DELETE: (id) => `admin/subjects/${id}`,
  },
  TOPICS: {
    GET_ALL: "admin/topics",
    CREATE: "admin/topics",
    UPDATE: (id) => `admin/topics/${id}`,
    DELETE: (id) => `admin/topics/${id}`,
  },
  CONTESTS: {
    GET_PUBLIC: "public/contests",
    GET_ALL: "admin/contests",
    GET_BY_ID: (id) => `admin/contests/${id}`,
    CREATE: "admin/contests",
    UPDATE: (id) => `admin/contests/${id}`,
    DELETE: (id) => `admin/contests/${id}`,
    SCHEDULED: "admin/contests/scheduled",
    SCHEDULE: (id) => `admin/contests/${id}/schedule`,
    ENTRY_FEE: (id) => `admin/contests/${id}/entry-fee`,
    PRIZE_POOL: (id) => `admin/contests/${id}/prize-pool`,
    LIVE: "admin/contests/live",
    LIVE_DETAILS: (id) => `admin/contests/${id}/live`,
    PARTICIPANTS: (id) => `admin/contests/${id}/participants`,
    RESULTS: (id) => `admin/contests/${id}/results`,
    STATISTICS: (id) => `admin/contests/${id}/statistics`,
  },
  FEE_TIERS: {
    GET_ALL: "admin/entry-fee-tiers",
    CREATE: "admin/entry-fee-tiers",
    UPDATE: (id) => `admin/entry-fee-tiers/${id}`,
    DELETE: (id) => `admin/entry-fee-tiers/${id}`,
  },
  PRIZE_TEMPLATES: {
    GET_ALL: "admin/prize-templates",
    CREATE: "admin/prize-templates",
    UPDATE: (id) => `admin/prize-templates/${id}`,
    DELETE: (id) => `admin/prize-templates/${id}`,
  },
  QUESTIONS: {
    GET_ALL: "admin/questions",
    GET_BY_ID: (id) => `admin/questions/${id}`,
    CREATE: "admin/questions",
    UPDATE: (id) => `admin/questions/${id}`,
    DELETE: (id) => `admin/questions/${id}`,
    UPLOAD: "admin/questions/upload",
    TEMPLATE_CSV: "admin/questions/template/csv",
  },
  FEATURES: {
    GET_PUBLIC: "public/features",
    GET_ALL: "admin/features",
    CREATE: "admin/features",
    UPDATE: (id) => `admin/features/${id}`,
    DELETE: (id) => `admin/features/${id}`,
  },
  USERS: {
    GET_ALL: "admin/users",
    GET_BY_ID: (id) => `admin/users/${id}`,
    DELETE: (id) => `admin/users/${id}`,
  },
  TRANSACTIONS: {
    GET_ALL: "admin/transactions",
    GET_BY_ID: (id) => `admin/transactions/${id}`,
    CREATE: "admin/transactions",
    EXPORT_CSV: "admin/transactions/export",
  },
  WITHDRAWALS: {
    GET_ALL: "admin/withdrawals",
    GET_BY_ID: (id) => `admin/withdrawals/${id}`,
    VERIFY: (id) => `admin/withdrawals/${id}/verify`,
  },
  FAQ: {
    GET_PUBLIC: "public/faq",
    GET_ALL: "admin/faq",
    CREATE: "admin/faq",
    UPDATE: (id) => `admin/faq/${id}`,
    DELETE: (id) => `admin/faq/${id}`,
  },
  SETTINGS: {
    GET_ALL: "admin/settings",
    CREATE: "admin/settings",
    UPDATE: (id) => `admin/settings/${id}`,
    DELETE: (id) => `admin/settings/${id}`,
  }
};